### ISSUE TITLE
ValueError: cannot reshape array of size 404829 into shape (6,newaxis)

### ISSUE THREAD

**Issue by ankistr** [Geodan/fill-holes-pointcloud#4]
The shape of my pointcloud is 

```
array([[-0.01216199,  0.12526932, -0.33400002],
       [-0.01041871,  0.12526932, -0.33400002],
       [-0.00867544,  0.12526932, -0.33400002],
       ...,
       [ 0.21376736, -0.1697637 , -0.273     ],
       [ 0.21519224, -0.1697637 , -0.273     ],
       [ 0.21661714, -0.1697637 , -0.273     ]])
```

my points array is

` {ndarray:(44981,3)}`

when I execute the code 

`_points = fill_holes(points) `

I got some errors 

```
Traceback (most recent call last):
  File "/opencv_pointcloud_viewer.py", line 321, in <module>
    suppress_qhull_errors=False)
  File "fill_holes.py", line 426, in fill_holes
    suppress_qhull_errors=suppress_qhull_errors
  File "fill_holes.py", line 352, in find_holes
    max_ratio_radius_area)
  File "fill_holes.py", line 81, in determine_big_triangles
    circumradii, areas = triangle_geometries(points, tri_simplices)
  File "fill_holes.py", line 42, in triangle_geometries
    triangles3 = triangles2.reshape((6, -1))
ValueError: cannot reshape array of size 404829 into shape (6,newaxis)

```
how can I fix this? 

I tried also with different values than default values for different parameters.

**Comment by K-M-Ibrahim-Khalilullah** [comment]
same problem

**Comment by marcosdiak** [comment]
Same issue here. I've played with different parameters but cannot make it work. Can you please help us @chrislcs, thanks!

**Comment by DavidCao1993** [comment]
same problem
