### ISSUE TITLE
Index 2 is out of bounds for axis 1 with size 2

### ISSUE THREAD

**Issue by tanishk27** [Geodan/fill-holes-pointcloud#7]
C:/Users/Tanishk_Rane/Downloads/fill-holes-pointcloud-master/raw_6b207c3f-92ab-4355-ab65-c4496c587c14.pcd
<class 'shapely.coords.CoordinateSequence'>
Traceback (most recent call last):
  File "__init__.py", line 14, in <module>
    fill_holes(points)
  File "C:\Users\Tanishk_Rane\Downloads\fill-holes-pointcloud-master\fill_holes\fill_holes.py", line 434, in fill_holes
    indices = np.asarray(h.exterior.coords)[:, 2].astype(int)
IndexError: index 2 is out of bounds for axis 1 with size 2

Sample Input for the fill_holes() function
C:/Users/Tanishk_Rane/Downloads/fill-holes-pointcloud-master/raw_6b207c3f-92ab-4355-ab65-c4496c587c14.pcd
[[ 0.1099903   0.5614326   0.00723594]
 [ 0.1054728   0.5614326   0.00901191]
 [ 0.1009404   0.5614326   0.01057232]
 ...
 [ 0.06300894  0.7604432  -0.06951104]
 [ 0.05372136  0.7604432  -0.1117434 ]
 [-0.07281303  0.7604432  -0.1168853 ]]

**Comment by tanishk27** [comment]
Please tell any solution if available

**Comment by Superkakayong** [comment]
Same issue encountered. Any solutions?
